### ISSUE TITLE
Circuit Breaker and retry policy fail with getAsyncExecution

### ISSUE THREAD

**Issue by nebulorum** [failsafe-lib/failsafe#268]
I migrated from 2.0.1 to anything after 2.1 and failed my unit test. Investigating a lot we found out that there some interaction between the RetryPolicy and CircuitBreaker and Async handler:

Our best guess is that the happy path for failed Retry and CircuitBreaker result in an NPE on `isFailure`:
```
Caused by: java.lang.NullPointerException
	at net.jodah.failsafe.PolicyExecutor.isFailure(PolicyExecutor.java:113)
	at net.jodah.failsafe.PolicyExecutor.postExecuteAsync(PolicyExecutor.java:96)
	at net.jodah.failsafe.PolicyExecutor.lambda$null$1(PolicyExecutor.java:87)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
	at net.jodah.failsafe.PolicyExecutor.lambda$supplyAsync$2(PolicyExecutor.java:87)
	at net.jodah.failsafe.RetryPolicyExecutor$1.call(RetryPolicyExecutor.java:101)
	at net.jodah.failsafe.internal.util.DelegatingScheduler.lambda$schedule$0(DelegatingScheduler.java:141)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

The following example is a bit large but covers several of the weird behaviours. retry by itself works perfectly. But depending of the policies on the CircuitBreaker there are various behaviour.  I commented out the onRetry, but is some of the cases there are thousands or `onRetry` calls. 

I simplified `doChain` and `doSub`. Originally `doChain` does a HTTP call and in 2.0.1 we check return status and call retry explicitly, but I'm convinced that this does not work correctly. So `doSub` is supposed to simulate an invalid return status and raises and exception to force a retry. This seems the correct way to handle failures.
 
```java 
public class Test1 {

    static AtomicInteger counter = new AtomicInteger(0);

    static public void main(String[] args) throws ExecutionException, InterruptedException {
        RetryPolicy<Object> retryPolicy = new RetryPolicy()
                .withMaxRetries(5)
                .withBackoff(100, 500, ChronoUnit.MILLIS, 1.1)
//TODO Uncomment for thousand of messages
//              .onRetry(o -> System.out.println("Retrying..." + o))
                .onRetriesExceeded(o -> {
                    System.out.println("out of luck" + o);
                });

        CircuitBreaker<Object> circuitBreaker = new CircuitBreaker<>()
                .onClose(() -> System.out.println("CB: Closed"))
                .onHalfOpen(() -> System.out.println("CB: HalfOpen"))
                .onOpen(() -> System.out.println("CB: Open"));

        circuitBreaker.close();
        runTest("Hang 1", retryPolicy, circuitBreaker);
        circuitBreaker.close();
        runTest("CB Open no retry before exist, one on CB Close",
                circuitBreaker, retryPolicy);

        circuitBreaker.close();
        runTest("Single retry, Circuit Breaker exception",
                circuitBreaker.withFailureThreshold(1).withDelay(Duration.ofMillis(500)), retryPolicy);
        circuitBreaker.close();
        runTest("NPE On second retry",
                retryPolicy, circuitBreaker.withFailureThreshold(3).withDelay(Duration.ofMillis(500)));

        //Works, by forcing call to be already higher
        System.out.println("\n---- Works --- ");
        counter.set(3);
        CompletableFuture<Object> o = Failsafe.with(retryPolicy)
                .getAsyncExecution(executeAction());
        System.out.println("Works ok: " + o.get());
        //Works
        counter.set(0);
        runTest("Will exhaust retries as expected", retryPolicy);

    }

    private static <P extends Policy<Object>> void runTest(String useCase, P... policies) {
        CompletableFuture<Object> answer;
        try {
            System.out.println("\n---- Failure " + useCase + " ----");
            counter.set(0);
            answer = Failsafe.with(Arrays.asList(policies)).getAsyncExecution(executeAction());
            answer.get(2, TimeUnit.SECONDS);
        } catch (Exception e) {
            System.out.println("RunTest: Exception after " + counter.get() + " calls with: " + e);
        }
    }

    private static AsyncSupplier<Object> executeAction() {
        return execution -> doChain().whenComplete((result, failure) -> {
            if (execution.complete(result, failure)) {
                execution.getLastResult();
                //TODO From example but this is not truly completed, since it can complete with failure.
                System.out.println("Completed?: failure=" + failure + " result=" + result);
            } else if (!execution.retry())
                System.out.println("Failed to retry: " + failure);
        });
    }

    private static CompletableFuture<String> doChain() {
        return doSub().thenCompose(x -> CompletableFuture.supplyAsync(() -> {
            if (x < 7) {
                throw new RuntimeException("Who?");
            }
            return "@" + (x * 10);
        }));
    }

    private static CompletableFuture<Integer> doSub() {

        return CompletableFuture.supplyAsync(() -> {
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            int i = counter.incrementAndGet();
            System.out.println("Call number = "  + i );
            return i;
        });
    }
}
```

**Comment by nebulorum** [comment]
Is there anything I can do to help?

**Comment by jhalterman** [comment]
@nebulorum Thanks for sharing this. It looks like there are a few test cases being covered here. Can you describe which of the test cases are producing an unexpected result, and what you think the expected result should be? Thinking of it that way, in terms of a failed assertion, is helpful.

**Comment by jhalterman** [comment]
@nebulorum I fixed an issue that caused the NPE in 664042cbbf9edbafd2f26c4441cf5487a4874aa2 and added more test coverage for Timeouts used with other policies. These will be released in 2.4.2 shortly. Let me know what you think.

**Comment by nebulorum** [comment]
@jhalterman thanks for fixing this. We will try to use this in our next patch round.

**Comment by jhalterman** [comment]
@nebulorum Look for the 3.0 release in the next couple of days, and you should be good with that version.
